

version: '3'
services:
  cryptoexchangestrapi:
    image: node:18.16.0-buster
    container_name: cryptoexchangestrapi
    network_mode: bridge
    ports:
      - "1337:1337"
    build:
      context: ../../
      dockerfile: DockerfileDevBackend
    volumes:
      - ../../backend:/cryptoexchangestrapi
    hostname: cryptoexchangestrapi
    depends_on:
      - cryptoexchangedbs
    links:
      - cryptoexchangedbs
  cryptoexchangefrontend:
    image: node:18.16.0-alpine3.17
    container_name: cryptoexchangefrontend
    network_mode: bridge
    ports:
      - "8080:8080"
    build:
      context: ../../
      dockerfile: Dockerfilefrontend
    volumes:
      - ./frontend:/cryptoexchangefrontend
  # MySQL Service for development only. 
  cryptoexchangedbs:
    image: mysql:8.0.28
    container_name: cryptoexchangedbs
    hostname: cryptoexchangedbs
    restart: unless-stopped
    env_file: .docker.env
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql/
    network_mode: bridge
